### ISSUE TITLE
Test examples do not work 

### ISSUE THREAD

**Issue by mw742** [595693085/DGraphDTA#10]
Hello 

I am trying to run the test examples given and want to see how they go. But I have tried both of them, davis and kiva, but they both returned the same error as below:

"effective drugs,effective prot: 2068 0
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    test_data = create_dataset_for_test(dataset)
  File "/home/wmm/GraphDTA/DGraphDTA/data_process.py", line 319, in create_dataset_for_test
    raise Exception('no protein or drug, run the script for datasets preparation.')
Exception: no protein or drug, run the script for datasets preparation.
" 

I have checked the code and noticed that, both examples given the protein all are uneffective as returned, as "effective drugs,effective prot: 2068 0" says, effective drug length is 2068 but the given protein is regarded as uneffective so the effective pros length is 0. Would you mind suggesting how to change this? Hope to hear form you.

**Comment by 595693085** [comment]
Hi, thanks for the attention to our work, here are some suggestion that may help you.
The error is caused by the failure to generate protein graphs. More specifically，the folders "data/davis/aln" and "data/davis/pconsc4" are none for davis dataset, and so do the KIBA dataset. So there are two ways to solve this.
1. First, you could install all the programs in the readme page, and change the code in "scripts.py" in line 120-124 to you own path, then run the script, the process need lots of time.
2. Or if you want to run the model right now, your can download the processed data which we uploaded on google cloud in the readme page, which is stored in "https://drive.google.com/open?id=1rqAopf_IaH3jzFkwXObQ4i-6bUUwizCv", unzip the file and put it to the corresponding folders, then you can train the model.
Hope it works, have a nice day~

**Comment by mw742** [comment]
> Hi, thanks for the attention to our work, here are some suggestion that may help you. The error is caused by the failure to generate protein graphs. More specifically，the folders "data/davis/aln" and "data/davis/pconsc4" are none for davis dataset, and so do the KIBA dataset. So there are two ways to solve this.
> 
> 1. First, you could install all the programs in the readme page, and change the code in "scripts.py" in line 120-124 to you own path, then run the script, the process need lots of time.
> 2. Or if you want to run the model right now, your can download the processed data which we uploaded on google cloud in the readme page, which is stored in "https://drive.google.com/open?id=1rqAopf_IaH3jzFkwXObQ4i-6bUUwizCv", unzip the file and put it to the corresponding folders, then you can train the model.
>    Hope it works, have a nice day~

Thank you very much! I have used your data and run the model successfullly!
